export const HORDE_IMAGE_MODEL_NAMES = [
  "2DN",
  "526Mix-Animated",
  "AAM XL",
  "AbsoluteReality",
  "Abyss OrangeMix",
  "AbyssOrangeMix-AfterDark",
  "ACertainThing",
  "AIO Pixel Art",
  "AlbedoBase XL 3.1",
  "AlbedoBase XL (SDXL)",
  "AMPonyXL",
  "Analog Diffusion",
  "Analog Madness",
  "Animagine XL",
  "Anime Illust Diffusion XL",
  "Anime Pencil Diffusion",
  "Anygen",
  "AnyLoRA",
  "Anything Diffusion",
  "Anything Diffusion Inpainting",
  "Anything v3",
  "Anything v5",
  "App Icon Diffusion",
  "Art Of Mtg",
  "Aurora",
  "A-Zovya RPG Inpainting",
  "Babes",
  "BB95 Furry Mix",
  "BB95 Furry Mix v14",
  "BigASP",
  "Blank Canvas XL",
  "BlenderMix Pony",
  "BweshMix",
  "CamelliaMix 2.5D",
  "Cetus-Mix",
  "Cheese Daddys Landscape Mix",
  "Cheyenne",
  "ChilloutMix",
  "Comic-Diffusion",
  "Counterfeit",
  "CyberRealistic Pony",
  "CyriousMix",
  "Dan Mumford Style",
  "Dark Sushi Mix",
  "Deliberate",
  "Deliberate 3.0",
  "Deliberate Inpainting",
  "Double Exposure Diffusion",
  "Dreamlike Diffusion",
  "DreamLikeSamKuvshinov",
  "Dreamshaper",
  "DreamShaper Inpainting",
  "DreamShaper XL",
  "DucHaiten",
  "DucHaiten Classic Anime",
  "Dungeons and Diffusion",
  "Dungeons n Waifus",
  "Edge Of Realism",
  "Eimis Anime Diffusion",
  "Elysium Anime",
  "Epic Diffusion",
  "Epic Diffusion Inpainting",
  "Ether Real Mix",
  "Experience",
  "ExpMix Line",
  "FaeTastic",
  "Fantasy Card Diffusion",
  "Flat-2D Animerge",
  "Flux.1-Schnell fp8 (Compact)",
  "Furry Epoch",
  "Fustercluck",
  "Galena Redux",
  "Ghibli Diffusion",
  "GhostMix",
  "Grapefruit Hentai",
  "GTA5 Artwork Diffusion",
  "HASDX",
  "Hassaku XL",
  "Healy's Anime Blend",
  "Hentai Diffusion",
  "HolyMix ILXL",
  "HRL",
  "ICBINP - I Can't Believe It's Not Photography",
  "ICBINP XL",
  "iCoMix",
  "iCoMix Inpainting",
  "Illuminati Diffusion",
  "Inkpunk Diffusion",
  "Jim Eidomode",
  "Juggernaut XL",
  "KaynegIllustriousXL",
  "Lawlas's yiff mix",
  "Liberty",
  "Lyriel",
  "majicMIX realistic",
  "MeinaMix",
  "MHXL - Aventis Horizon",
  "Midjourney PaintArt",
  "Mistoon Anime",
  "ModernArt Diffusion",
  "MoonMix Fantasy",
  "Movie Diffusion",
  "NatViS",
  "Neurogen",
  "NeverEnding Dream",
  "NEW ERA",
  "noobEvo",
  "noob_v_pencil XL",
  "Nova Anime XL",
  "Nova Furry Pony",
  "NTR MIX IL-Noob XL",
  "Pastel Mix",
  "Perfect World",
  "Photon",
  "Poison",
  "Pony Diffusion XL",
  "Pony Realism",
  "PPP",
  "Prefect Pony",
  "Pretty 2.5D",
  "Project Unreal Engine 5",
  "Quiet Goodnight XL",
  "Qwen-Image_fp8",
  "RealBiter",
  "Real Dos Mix",
  "Realism Engine",
  "Realistic Vision",
  "Realistic Vision Inpainting",
  "Reliberate",
  "Rev Animated",
  "RPG",
  "Sci-Fi Diffusion",
  "SD-Silicon",
  "SDXL 1.0",
  "Something",
  "Stable Cascade 1.0",
  "stable_diffusion",
  "stable_diffusion_2.1",
  "stable_diffusion_inpainting",
  "SwamPonyXL",
  "ToonYou",
  "TUNIX Pony",
  "Uhmami",
  "Unstable Diffusers XL",
  "Unstable Ink Dream",
  "URPM",
  "Vector Art",
  "WAI-ANI-NSFW-PONYXL",
  "WAI-CUTE Pony",
  "waifu_diffusion",
  "WAI-NSFW-illustrious-SDXL",
  "Western Animation Diffusion",
  "White Pony Diffusion 4",
  "Woop-Woop Photo",
  "Yiffy",
  "ZavyChromaXL",
  "Zeipher Female Model",
  "Z-Image-Turbo",
  "Ultraspice",
] as const;

export const HORDE_IMAGE_DISPLAY_NAMES: Record<string, string> = {
  stable_diffusion: "Stable Diffusion",
  "stable_diffusion_2.1": "Stable Diffusion 2.1",
  stable_diffusion_inpainting: "Stable Diffusion Inpainting",
  waifu_diffusion: "Waifu Diffusion",
  "Qwen-Image_fp8": "Qwen Image",
};

function toHordeImageDisplayName(modelName: string) {
  if (HORDE_IMAGE_DISPLAY_NAMES[modelName]) {
    return HORDE_IMAGE_DISPLAY_NAMES[modelName];
  }

  return modelName
    .replaceAll("_", " ")
    .replaceAll(".", " ")
    .replaceAll("-", " ")
    .replace(/\s+/g, " ")
    .trim();
}

export const hordeImageModelOptions = HORDE_IMAGE_MODEL_NAMES.map((name) => ({
  apiName: name,
  displayName: toHordeImageDisplayName(name),
  id: `horde/${name}`,
  label: toHordeImageDisplayName(name),
}));
